// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricsMetricExchange metrics metric exchange
//
// swagger:model metrics.MetricExchange
type MetricsMetricExchange struct {

	// delta
	Delta int64 `json:"delta,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// type
	Type string `json:"type,omitempty"`

	// value
	Value float64 `json:"value,omitempty"`
}

// Validate validates this metrics metric exchange
func (m *MetricsMetricExchange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metrics metric exchange based on context it is used
func (m *MetricsMetricExchange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricsMetricExchange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricsMetricExchange) UnmarshalBinary(b []byte) error {
	var res MetricsMetricExchange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
